# Generated by Django 4.2.5 on 2023-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='academia',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
